import { ApiWebBaseEndpoints } from './categories/ApiWebBaseEndpoints';
import { CommentsEndpoints } from './categories/CommentsEndpoints';
import { ContentEndpoints } from './categories/ContentEndpoints';
import { DataEndpoints } from './categories/DataEndpoints';
import { DocumentsEndpoints } from './categories/DocumentsEndpoints';
import { DelegatesEndpoints } from './categories/DelegatesEndpoints';
import { WebEndpoints } from './categories/WebEndpoints';
import { SortingEndpoints } from './categories/SortingEndpoints';
import { FilteringEndpoints } from './categories/FilteringEndpoints';
import { HighlightsEndpoints } from './categories/HighlightsEndpoints';
import { LoggingEndpoints } from './categories/LoggingEndpoints';
import { NewsEndpoints } from './categories/NewsEndpoints';
import { NotesEndpoints } from './categories/NotesEndpoints';
import { ProjectsEndpoints } from './categories/ProjectsEndpoints';
import { SearchingEndpoints } from './categories/SearchingEndpoints';
import { SnapshotsEndpoints } from './categories/SnapshotsEndpoints';
import { UiEndpoints } from './categories/UiEndpoints';
import { VersionEndpoints } from './categories/VersionEndpoints';
import { TasksEndpoints } from './categories/TasksEndpoints';
import { TeamsEndpoints } from './categories/TeamsEndpoints';
import { TodosEndpoints } from './categories/TodosEndpoints';
import { UsersEndpoints } from './categories/UsersEndpoints';

import { AuthEndpoints } from './categories/AuthEndpoints';
import { BlogsEndpoints } from './categories/BlogsEndpoints';
import { CalendarEndpoints } from './categories/CalendarEndpoints';
import { ChatEndpoints } from './categories/ChatEndpoints';
import { ClientEndpoints } from './categories/ClientEndpoints';
import { CollaborationToolsEndpoints } from './categories/CollaborationToolsEndpoints';
import { CommunicationEndpoints } from './categories/CommunicationEndpoints';
import { CommunityInteractionEndpoints } from './categories/CommunityInteractionEndpoints';
import { CryptoEndpoints } from './categories/CryptoEndpoints';
import { DataProvidersEndpoints } from './categories/DataProvidersEndpoints';
import { DexEndpoints } from './categories/DexEndpoints';
import { DetailsEndpoints } from './categories/DetailsEndpoints';
import { DonationsEndpoints } from './categories/DonationsEndpoints';
import { DrawingEndpoints } from './categories/DrawingEndpoints';
import { ExternalAuthEndpoints } from './categories/ExternalAuthEndpoints';
import { FeedbackEndpoints } from './categories/FeedbackEndpoints';
import { FilesEndpoints } from './categories/FilesEndpoints';
import { FreelancersEndpoints } from './categories/FreelancersEndpoints';
import { GeneratorsEndpoints } from './categories/GeneratorsEndpoints';
import { GlobalCollaborationEndpoints } from './categories/GlobalCollaborationEndpoints';
import { MarkerEndpoints } from './categories/MarkerEndpoints';
import { ModeratorsEndpoints } from './categories/ModeratorsEndpoints';
import { MonetizationEndpoints } from './categories/MonetizationEndpoints';
import { ParameterCustomizationEndpoints } from './categories/ParameterCustomizationEndpoints';
import { PaymentEndpoints } from './categories/PaymentEndpoints';
import { PersonasEndpoints } from './categories/PersonasEndpoints';
import { PhasesEndpoints } from './categories/PhasesEndpoints';
import { ProjectManagementEndpoints } from './categories/ProjectManagementEndpoints';
import { ProjectOwnerEndpoints } from './categories/ProjectOwnerEndpoints';
import { RandomWalkEndpoints } from './categories/RandomWalkEndpoints';
import { RegistrationEndpoints } from './categories/RegistrationEndpoints';
import { ReportsEndpoints } from './categories/ReportsEndpoints';
import { SecurityEndpoints } from './categories/SecurityEndpoints';
import { StateGovCitiesEndpoints } from './categories/StateGovCitiesEndpoints';
import { TeamManagementEndpoints } from './categories/TeamManagementEndpoints';
import { ThemeEndpoints } from './categories/ThemeEndpoints';
import { ToolbarEndpoints } from './categories/ToolbarEndpoints';
import { TradingEndpoints } from './categories/TradingEndpoints';
import { UserManagementEndpoints } from './categories/UserManagementEndpoints';
import { UserRolesEndpoints } from './categories/UserRolesEndpoints';
import { UserRolesNFTEndpoints } from './categories/UserRolesNFTEndpoints';
import { UserSettingsEndpoints } from './categories/UserSettingsEndpoints';
import { VideosEndpoints } from './categories/VideosEndpoints';
import { DatabaseEndpoints } from './categories/DatabaseEndpoints';
import { ApiConfigEndpoints } from './categories/ApiConfigEndpoints';
import { DevEndpoints } from './categories/DevEndpoints';
import { DocumentEndpoints } from './categories/DocumentEndpoints';
import { ParticipantsEndpoints } from './categories/ParticipantsEndpoints';
import { MessagesEndpoints } from './categories/MessagesEndpoints';
import { ScreenSharingEndpoints } from './categories/ScreenSharingEndpoints';
import { DataAnalysisEndpoints } from './categories/DataAnalysisEndpoints';
import { LogsEndpoints } from './categories/LogsEndpoints';
import { BatchEndpoints } from './categories/BatchEndpoints';

export interface EndpointConfig {
  path: string;
  method: "GET" | "POST" | "PUT" | "DELETE";
}

export interface EndpointConfigurations {
  apiWebBase: ApiWebBaseEndpoints;
  comments: CommentsEndpoints;
  content: ContentEndpoints;
  data: DataEndpoints;
  documents: DocumentsEndpoints;
  delegates: DelegatesEndpoints;
  web: WebEndpoints;
  sorting: SortingEndpoints;
  filtering: FilteringEndpoints;
  highlights: HighlightsEndpoints;
  logging: LoggingEndpoints;
  news: NewsEndpoints;
  notes: NotesEndpoints;
  projects: ProjectsEndpoints;
  searching: SearchingEndpoints;
  snapshots: SnapshotsEndpoints;
  ui: UiEndpoints;
  version: VersionEndpoints;
  tasks: TasksEndpoints;
  teams: TeamsEndpoints;
  todos: TodosEndpoints;
  users: UsersEndpoints;

  auth: AuthEndpoints;
  blogs: BlogsEndpoints;
  calendar: CalendarEndpoints;
  chat: ChatEndpoints;
  client: ClientEndpoints;
  collaborationTools: CollaborationToolsEndpoints;
  communication: CommunicationEndpoints;
  communityInteraction: CommunityInteractionEndpoints;
  crypto: CryptoEndpoints;
  dataProviders: DataProvidersEndpoints;
  dex: DexEndpoints;
  details: DetailsEndpoints;
  donations: DonationsEndpoints;
  drawing: DrawingEndpoints;
  externalAuth: ExternalAuthEndpoints;
  feedback: FeedbackEndpoints;
  files: FilesEndpoints;
  freelancers: FreelancersEndpoints;
  generators: GeneratorsEndpoints;
  globalCollaboration: GlobalCollaborationEndpoints;
  marker: MarkerEndpoints;
  moderators: ModeratorsEndpoints;
  monetization: MonetizationEndpoints;
  parameterCustomization: ParameterCustomizationEndpoints;
  payment: PaymentEndpoints;
  personas: PersonasEndpoints;
  phases: PhasesEndpoints;
  projectManagement: ProjectManagementEndpoints;
  projectOwner: ProjectOwnerEndpoints;
  randomWalk: RandomWalkEndpoints;
  registration: RegistrationEndpoints;
  reports: ReportsEndpoints;
  security: SecurityEndpoints;
  stateGovCities: StateGovCitiesEndpoints;
  teamManagement: TeamManagementEndpoints;
  theme: ThemeEndpoints;
  toolbar: ToolbarEndpoints;
  trading: TradingEndpoints;
  userManagement: UserManagementEndpoints;
  userRoles: UserRolesEndpoints;
  userRolesNFT: UserRolesNFTEndpoints;
  userSettings: UserSettingsEndpoints;
  videos: VideosEndpoints;
  database: DatabaseEndpoints;
  apiConfig: ApiConfigEndpoints;
  dev: DevEndpoints;
  document: DocumentEndpoints;
  participants: ParticipantsEndpoints;
  messages: MessagesEndpoints;
  screenSharing: ScreenSharingEndpoints;
  dataAnalysis: DataAnalysisEndpoints;
  logs: LogsEndpoints;
  batch: BatchEndpoints;
}