// generate-commands-doc.ts
import fs from 'fs';
import path from 'path';
import { StructureValidator } from '@/app/generators/corrections/StructureValidator';

interface PackageJson {
  // Core identification
  name: string;
  version: string;
  description?: string;
  keywords?: string[];
  
  // Entry points
  main?: string;
  module?: string;
  types?: string;
  browser?: string;
  
  // Dependencies - CRITICAL for your multi-feature platform
  dependencies: Record<string, string>;
  devDependencies: Record<string, string>;
  peerDependencies?: Record<string, string>;
  optionalDependencies?: Record<string, string>;
  
  // Scripts - Essential for your complex build process
  scripts: Record<string, string>;
  
  // Framework & runtime requirements
  engines?: {
    node?: string;
    npm?: string;
    yarn?: string;
  };
  
  // Platform configuration
  private?: boolean;
  type?: 'module' | 'commonjs';
  
  // Workspaces - Important for monorepo structure (likely for your multi-feature app)
  workspaces?: string[];
  
  // Modern exports
  exports?: PackageJsonExports;
  
  // Additional metadata
  author?: string | { name: string; email?: string; url?: string };
  license?: string;
  repository?: string | { type: string; url: string };
}

interface PackageJsonExports {
  '.': string | { 
    import?: string;
    require?: string;
    types?: string;
    default?: string;
  };
  './package.json': string;
  [key: `./${string}`]: string | { 
    import?: string;
    require?: string;
    types?: string;
    default?: string;
  };
}

function generateCommandsDoc(): void {
  const structureValidator = new StructureValidator();
  const packageJson = await structureValidator.getPackageJsonData();
  
  if (!packageJson) {
    console.error('❌ Could not read package.json');
    return;
  }

  const categories = {
    '🚀 Development & Build': ['dev', 'build', 'start', 'lint'],
    '🔍 Code Analysis & Quality': ['analyze:', 'type-check', 'lint:types', 'test:types', 'validate:build'],
    '📊 Project Structure & Roadmaps': ['generate:tree', 'generate:roadmaps', 'generate:analysis'],
    '🛠️ Code Corrections & Fixes': ['generate:corrections'],
    '🔄 Development Workflows': ['dev:with-'],
    '📸 Snapshot Management': ['snapshots:', 'data:reset'],
    '⚡ Quick Actions': ['quick:'],
    '🔒 Pre-commit & Pre-push Hooks': ['pre-commit', 'pre-push'],
    '📱 Mobile & React Native': ['start:mobile', 'android', 'ios'],
    '🌐 Web & React Scripts': ['start_react', 'build_react', 'web', 'eject'],
    '🖥️ Server & Backend': ['server', 'ollama']
  };

  let markdown = `# Development Commands Reference\n\n`;
  markdown += `*This file is automatically generated from package.json. Do not edit manually.*\n\n`;
  markdown += `## 📋 Quick Navigation\n\n`;

  // Table of contents
  Object.keys(categories).forEach(category => {
    const anchor = category.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    markdown += `- [${category}](#${anchor})\n`;
  });

  markdown += `\n---\n\n`;

  // Generate each section
  Object.entries(categories).forEach(([category, patterns]) => {
    markdown += `## ${category}\n\n`;
    markdown += `| Command | Purpose | Usage |\n`;
    markdown += `|---------|---------|--------|\n`;

    const scriptsInCategory = Object.entries(packageJson.scripts)
      .filter(([name]) => patterns.some(pattern => name.startsWith(pattern) || name === pattern))
      .sort();

    if (scriptsInCategory.length === 0) {
      markdown += `| *No scripts in this category* | | |\n`;
    } else {
      scriptsInCategory.forEach(([name, command]) => {
        // Extract purpose from command (you could make this smarter)
        const purpose = getScriptPurpose(name, command);
        markdown += `| \`pnpm ${name}\` | ${purpose} | \`pnpm ${name}\` |\n`;
      });
    }
    markdown += '\n';
  });

  // Write the file
  const outputPath = path.resolve(process.cwd(), 'DEV_COMMANDS.md');
  fs.writeFileSync(outputPath, markdown);
  console.log('✅ DEV_COMMANDS.md generated from package.json');
}

function getScriptPurpose(name: string, command: string): string {
  // You can expand this mapping as needed
  const purposeMap: Record<string, string> = {
    'dev': 'Start development server',
    'build': 'Build for production',
    'start': 'Start production server',
    'lint': 'Run ESLint',
    'generate:corrections': 'Full code correction analysis - Finds compilation errors, structural issues, and security problems',
    'quick:fixes': 'Show quick fixes - Easy wins under 5 minutes (TypeScript code fixes)',
    // Add more mappings as needed
  };

  return purposeMap[name] || `Runs: ${command.split(' ')[0]}`;
}

// Run if called directly
if (require.main === module) {
  generateCommandsDoc();
}

export { generateCommandsDoc };
export type { PackageJson, PackageJsonExports }