//DocumentPhaseTypeEnum.ts

export enum DocumentPhaseTypeEnum {
  Ideation = "ideation",
  Drafting = "drafting",
  Review = "review",
  Approval = "approval",
  Revision = "revision",
  Finalization = "finalization",
  Publication = "publication",
  Distribution = "distribution",
  Feedback = "feedback",
  Archiving = "archiving",
  Deletion = "deletion",
  Suspension = "suspension",
  Restoration = "restoration",
  ConfidentialReview = "confidential_review",
  PublicReview = "public_review",
  EmergencyUpdate = "emergency_update",
  HistoricalReview = "historical_review",
  Encryption = "encryption",
  Decryption = "decryption",
  Formatting = "formatting",
  MetadataAssignment = "metadata_assignment",
  Collaboration = "collaboration",
  Translation = "translation",
  LegalReview = "legal_review",
  CommunityEngagement = "community_engagement",
  PodcastPreparation = "podcast_preparation",
  CryptoAnalysis = "crypto_analysis",
  MarketResearch = "market_research",
  BusinessStrategy = "business_strategy",
  DataAnalysis = "data_analysis",
  Presentation = "presentation",
  ReportGeneration = "report_generation",
  TemplateCreation = "template_creation",
  ImageProcessing = "image_processing",
  FileHandling = "file_handling",
  URLLinking = "url_linking",
  Other = "other",
}


