// cryptoConfig.ts
import { CryptoEndpoints } from '../types/categories/CryptoEndpoints';
import { BASE_URL } from './baseUrl';

export const cryptoConfig: CryptoEndpoints = {
  settings: { path: `${BASE_URL}/api/crypto/settings`, method: "GET" },
  list: { path: `${BASE_URL}/api/crypto/list`, method: "GET" },
  fetchCryptoData: { path: `${BASE_URL}/api/crypto/data`, method: "GET" },
  fetchCryptoDetails: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}`, method: "GET" }),
  addCrypto: { path: `${BASE_URL}/api/crypto/add`, method: "POST" },
  removeCrypto: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/remove`, method: "DELETE" }),
  updateCrypto: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/update`, method: "PUT" }),
  getHistoricalData: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/historical-data`, method: "GET" }),
  getNews: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/news`, method: "GET" }),
  getPricePrediction: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/price-prediction`, method: "GET" }),
  getTransactions: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/transactions`, method: "GET" }),
  getExchangeRates: { path: `${BASE_URL}/api/crypto/exchange-rates`, method: "GET" },
  getMarketCap: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/market-cap`, method: "GET" }),
  getSocialSentiment: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/social-sentiment`, method: "GET" }),
  getCommunityDiscussions: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/community-discussions`, method: "GET" }),
  getTechnicalAnalysis: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/technical-analysis`, method: "GET" }),
  getMarketTrend: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/market-trend`, method: "GET" }),
  getTradingVolume: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/trading-volume`, method: "GET" }),
  getCommunitySentiment: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/community-sentiment`, method: "GET" }),
  getSocialImpactAnalysis: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/social-impact-analysis`, method: "GET" }),
  getGlobalAdoptionTrends: (cryptoId: string) => ({ path: `${BASE_URL}/api/crypto/${cryptoId}/global-adoption-trends`, method: "GET" }),
  getUserContributionRewards: (userId: string) => ({ path: `${BASE_URL}/api/crypto/users/${userId}/contribution-rewards`, method: "GET" }),
  getCommunityProjects: { path: `${BASE_URL}/api/crypto/community-projects`, method: "GET" },
  getDeveloperCompensation: { path: `${BASE_URL}/api/crypto/developer-compensation`, method: "GET" },
  getGlobalCollaborationTools: { path: `${BASE_URL}/api/crypto/global-collaboration-tools`, method: "GET" },
  getMonetizationOpportunities: { path: `${BASE_URL}/api/crypto/monetization-opportunities`, method: "GET" },
  getRevenueDistribution: { path: `${BASE_URL}/api/crypto/revenue-distribution`, method: "GET" },
  getImpactAssessment: { path: `${BASE_URL}/api/crypto/impact-assessment`, method: "GET" },
  getMarketData: { path: `${BASE_URL}/api/crypto/market-data`, method: "GET" },
  getPortfolioSummary: { path: `${BASE_URL}/api/crypto/portfolio-summary`, method: "GET" },
  getTopGainers: { path: `${BASE_URL}/api/crypto/top-gainers`, method: "GET" },
  getTopLosers: { path: `${BASE_URL}/api/crypto/top-losers`, method: "GET" },
  getExchangeListings: { path: `${BASE_URL}/api/crypto/exchange-listings`, method: "GET" },
  getMarketTrends: { path: `${BASE_URL}/api/crypto/market-trends`, method: "GET" },
  getTransactionHistory: { path: `${BASE_URL}/api/crypto/transaction-history`, method: "GET" },
  getWalletBalance: { path: `${BASE_URL}/api/crypto/wallet-balance`, method: "GET" },
  getAlertSettings: { path: `${BASE_URL}/api/crypto/alert-settings`, method: "GET" },
  getPriceAlerts: { path: `${BASE_URL}/api/crypto/price-alerts`, method: "GET" },
  getInsights: { path: `${BASE_URL}/api/crypto/insights`, method: "GET" },
  getStakingRewards: { path: `${BASE_URL}/api/crypto/staking-rewards`, method: "GET" },
  getLiquidityPools: { path: `${BASE_URL}/api/crypto/liquidity-pools`, method: "GET" },
  getNFTMarketplace: { path: `${BASE_URL}/api/crypto/nft-marketplace`, method: "GET" },
  getGovernanceProposals: { path: `${BASE_URL}/api/crypto/governance-proposals`, method: "GET" },
  getChainAnalysis: { path: `${BASE_URL}/api/crypto/chain-analysis`, method: "GET" },
  getDEXTransactions: { path: `${BASE_URL}/api/crypto/dex-transactions`, method: "GET" },
  getRegulatoryCompliance: { path: `${BASE_URL}/api/crypto/regulatory-compliance`, method: "GET" },
  getDeveloperDocumentation: { path: `${BASE_URL}/api/crypto/developer-docs`, method: "GET" },
  getIntegrationGuides: { path: `${BASE_URL}/api/crypto/integration-guides`, method: "GET" },
  getDeveloperTools: { path: `${BASE_URL}/api/crypto/developer-tools`, method: "GET" },
  getDeveloperResources: { path: `${BASE_URL}/api/crypto/developer-resources`, method: "GET" },
  getDeveloperEcosystem: { path: `${BASE_URL}/api/crypto/developer-ecosystem`, method: "GET" },
  getDeveloperCommunity: { path: `${BASE_URL}/api/crypto/developer-community`, method: "GET" },
};