// SecurityFeatureEnum.ts
export enum SecurityFeatureEnum {
  TwoFactorAuthentication = 'TwoFactorAuthentication',
  Encryption = 'Encryption',
  SecureSocketLayer = 'SecureSocketLayer',
  Firewalls = 'Firewalls',
  IntrusionDetectionSystem = 'IntrusionDetectionSystem',
  AccessControl = 'AccessControl',
  AntivirusSoftware = 'AntivirusSoftware',
  SecureBoot = 'SecureBoot',
  DataBackup = 'DataBackup',
  VPN = 'VPN',
  BiometricAuthentication = 'BiometricAuthentication',
  MultiFactorAuthentication = 'MultiFactorAuthentication',
  NetworkSegmentation = 'NetworkSegmentation',
  SecurityPolicies = 'SecurityPolicies',
  IncidentResponsePlan = 'IncidentResponsePlan',
  PenetrationTesting = 'PenetrationTesting',
  SecurityTraining = 'SecurityTraining',
  VulnerabilityAssessment = 'VulnerabilityAssessment',
  IdentityManagement = 'IdentityManagement',
  SecurityAudit = 'SecurityAudit',
  SecureDevelopmentLifecycle = 'SecureDevelopmentLifecycle',
  ThreatModeling = 'ThreatModeling',
  SecurityInformationEventManagement = 'SecurityInformationEventManagement',
}
