"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var idleTimeoutHooks_1 = require("../components/hooks/idleTimeoutHooks");
var userSettings = {
    communicationMode: "text",
    enableRealTimeUpdates: true,
    defaultFileType: "document",
    allowedFileTypes: ["document"],
    enableGroupManagement: true,
    enableTeamManagement: true,
    idleTimeout: (0, idleTimeoutHooks_1.default)(),
    startIdleTimeout: (0, idleTimeoutHooks_1.default)(),
    idleTimeoutDuration: 0,
    activePhase: "current phase",
    realTimeChatEnabled: false,
    todoManagementEnabled: false,
    notificationEmailEnabled: false,
    analyticsEnabled: false,
    twoFactorAuthenticationEnabled: false,
    projectManagementEnabled: false,
    documentationSystemEnabled: false,
    versionControlEnabled: false,
    userProfilesEnabled: false,
    accessControlEnabled: false,
    taskManagementEnabled: false,
    loggingAndNotificationsEnabled: false,
    securityFeaturesEnabled: false,
    collaborationPreference1: undefined,
    collaborationPreference2: undefined,
    theme: "",
    language: "",
    fontSize: 0,
    darkMode: false,
    enableEmojis: false,
    enableGIFs: false,
    emailNotifications: false,
    pushNotifications: false,
    notificationSound: "",
    timeZone: "",
    dateFormat: "",
    timeFormat: "",
    defaultProjectView: "",
    taskSortOrder: "",
    showCompletedTasks: false,
    projectColorScheme: "",
    showTeamCalendar: false,
    teamViewSettings: [],
    defaultTeamDashboard: "",
    passwordExpirationDays: 0,
    privacySettings: [],
    thirdPartyApiKeys: {},
    externalCalendarSync: false,
    dataExportPreferences: [],
    dashboardWidgets: [],
    customTaskLabels: [],
    customProjectCategories: [],
    customTags: [],
    additionalPreference1: undefined,
    additionalPreference2: undefined,
    formHandlingEnabled: false,
    paginationEnabled: false,
    modalManagementEnabled: false,
    sortingEnabled: false,
    notificationSoundEnabled: false,
    localStorageEnabled: false,
    clipboardInteractionEnabled: false,
    deviceDetectionEnabled: false,
    loadingSpinnerEnabled: false,
    errorHandlingEnabled: false,
    toastNotificationsEnabled: false,
    datePickerEnabled: false,
    themeSwitchingEnabled: false,
    imageUploadingEnabled: false,
    passwordStrengthEnabled: false,
    browserHistoryEnabled: false,
    geolocationEnabled: false,
    webSocketsEnabled: false,
    dragAndDropEnabled: false,
    idleTimeoutEnabled: false,
    enableAudioChat: false,
    enableVideoChat: false,
    enableFileSharing: false,
    enableBlockchainCommunication: false,
    enableDecentralizedStorage: false,
};
exports.default = userSettings;
