// createMessage.ts
import { Message } from "@/app/generators/GenerateChatInterfaces";
import { v4 as uuidv4 } from "uuid"; // Ensure you have 'uuid' installed or use another method for unique IDs
import { User } from "../users/User";
import { ChatRoom } from "../calendar/CalendarSlice";

export const createMessage = (
  type: string,
  content: string,
  additionalData?: any
): Message => {
  return {
    id: uuidv4(),
    type: type,
    senderId: "system",
    sender: {
      id: "system",
      username: "System",
      firstName: "System",
      lastName: "User",
      email: "system@example.com",
      tags: [],
      isUserMessage: false,
      tier: "",
      token: "",
      uploadQuota: 0,
      avatarUrl: "",
      bannerUrl: "",
      workspaceUrl: "",
      workspaces: [],
      products: [],
      roles: [],
      permissions: [],
      status: "",
      statusText: "",
      activeProduct: "",
      activeWorkspace: "",
      activeRole: "",
      activePermissions: [],
      activeWorkspacePermissions: [],
      activeProductPermissions: [],
      activeRolePermissions: [],
      activeWorkspaceRoles: [],
      activeProductRoles: [],
      activeWorkspaceProducts: [],
      activeProductWorkspaces: [],
      activeRoleWorkspaces: [],
      activeRoleProducts: [],
    } as unknown as User,
    channel: {
      id: "",
      creatorId: "",
      topics: [],
      messages: [],
      users: [],
    },
    channelId: "",
    content: content,
    additionalData: additionalData || {},
    tags: [],
    userId: undefined,
    timestamp: new Date().toISOString(),
    text: content,
    isUserMessage: false,
    receiver: undefined,
    description: "",
    username: "System",
    firstName: "System",
    lastName: "User",
    email: "system@example.com",
    isOnline: false,
    lastSeen: new Date().toISOString(),
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    imageUrl: "",
    bio: "",
    website: "",
    location: "",
    coverImageUrl: "",
    following: [],
    followers: [],
    notifications: {
      email: false,
      push: false,
      sms: false,
      chat: false,
      audioCall: false,
      videoCall: false,
      screenShare: false,
      mention: false,
      reaction: false,
      follow: false,
      poke: false,
      activity: false,
      thread: false,
      inviteAccepted: false,
      calendar: false,
      task: false,
      file: false,
      meeting: false,
      directMessage: false,
      announcement: false,
      reminder: false,
      project: false,
      enabled: false,
      notificationType: "sms",
    },
    chatRooms: [],
    blockedUsers: [],
    blockedBy: [],
    tier: "",
    token: "",
    uploadQuota: 0,
    avatarUrl: "",
    bannerUrl: "",
    workspaceUrl: "",
    workspaces: [],
    products: [],
    roles: [],
    permissions: [],
    status: "",
    statusText: "",
    activeProduct: "",
    activeWorkspace: "",
    activeRole: "",
    activePermissions: [],
    activeWorkspacePermissions: [],
    activeProductPermissions: [],
    activeRolePermissions: [],
    activeWorkspaceRoles: [],
    activeProductRoles: [],
    activeWorkspaceProducts: [],
    activeProductWorkspaces: [],
    activeRoleWorkspaces: [],
    activeRoleProducts: [],
  };
};
