// DocumentsEndpoints.ts
import { EndpointConfig } from '../EndpointConfigurations';

export interface DocumentsEndpoints {
  list: EndpointConfig;
  single: (documentId: string) => EndpointConfig;
  add: EndpointConfig;
  remove: (documentId: string) => EndpointConfig;
  update: (documentId: string) => EndpointConfig;
  download: (documentId: string) => EndpointConfig;
  search: EndpointConfig;
  filter: EndpointConfig;
  upload: EndpointConfig;
  share: EndpointConfig;
  lock: EndpointConfig;
  unlock: EndpointConfig;
  archive: EndpointConfig;
  restore: EndpointConfig;
  move: EndpointConfig;
  copy: EndpointConfig;
  rename: EndpointConfig;
  changePermissions: EndpointConfig;
  merge: EndpointConfig;
  split: EndpointConfig;
  validate: EndpointConfig;
  encrypt: EndpointConfig;
  decrypt: EndpointConfig;
  trackChanges: EndpointConfig;
  compare: EndpointConfig;
  tag: EndpointConfig;
  categorize: EndpointConfig;
  customizeView: EndpointConfig;
  comment: EndpointConfig;
  mentionUser: EndpointConfig;
  assignTask: EndpointConfig;
  requestReview: EndpointConfig;
  approve: EndpointConfig;
  reject: EndpointConfig;
  requestFeedback: EndpointConfig;
  provideFeedback: EndpointConfig;
  resolveFeedback: EndpointConfig;
  collaborativeEditing: EndpointConfig;
  smartTagging: EndpointConfig;
  annotation: EndpointConfig;
  activityLogging: EndpointConfig;
  intelligentSearch: EndpointConfig;
  createVersion: EndpointConfig;
  revertVersion: EndpointConfig;
  viewHistory: EndpointConfig;
  compareVersions: EndpointConfig;
  grantAccess: EndpointConfig;
  revokeAccess: EndpointConfig;
  managePermissions: EndpointConfig;
  initiateWorkflow: EndpointConfig;
  automateTasks: EndpointConfig;
  triggerEvents: EndpointConfig;
  approvalWorkflow: EndpointConfig;
  lifecycleManagement: EndpointConfig;
  connectExternalSystem: EndpointConfig;
  synchronizeStorage: EndpointConfig;
  importFromExternal: EndpointConfig;
  exportToExternal: EndpointConfig;
  generateReport: EndpointConfig;
  exportReport: EndpointConfig;
  scheduleReport: EndpointConfig;
  customizeReport: EndpointConfig;
  manageSubscriptions: EndpointConfig;
  handleSubscriptions: EndpointConfig;
  notificationSettings: EndpointConfig;
  notifyChanges: EndpointConfig;
  backup: EndpointConfig;
  retrieveBackup: EndpointConfig;
  redact: EndpointConfig;
  accessControls: EndpointConfig;
  templates: EndpointConfig;
}