// tasksConfig.ts
import { TasksEndpoints } from '@/app/typings/categories/TasksEndpoints';

export const tasksConfig: TasksEndpoints = {
  list: { path: "/api/tasks", method: "GET" },
  single: (taskId) => ({ path: `/api/tasks/${taskId}`, method: "GET" }),
  add: { path: "/api/tasks", method: "POST" },
  remove: (taskId) => ({ path: `/api/tasks/${taskId}`, method: "DELETE" }),
  update: (taskId) => ({ path: `/api/tasks/${taskId}`, method: "PUT" }),
  completeAll: { path: "/api/tasks/complete-all", method: "POST" },
  toggle: (taskId) => ({ path: `/api/tasks/${taskId}/toggle`, method: "POST" }),
  removeMultiple: { path: "/api/tasks/remove-multiple", method: "POST" },
  toggleMultiple: { path: "/api/tasks/toggle-multiple", method: "POST" },
  assign: (taskId, teamId) => ({
    path: `/api/tasks/${taskId}/assign/${teamId}`,
    method: "POST",
  }),
  unassign: (taskId) => ({ path: `/api/todos/${taskId}/unassign`, method: "POST" }),
  initializeUserData: { path: "/api/initialize-user-data", method: "POST" },
  handleQuestionnaireSubmit: { path: "/api/handle-questionnaire-submit", method: "POST" },
  bulkAssign: { path: "/api/tasks/bulk-assign", method: "POST" },
  bulkUnassign: { path: "/api/tasks/bulk-unassign", method: "POST" },
  filter: (status, dueDate, assignedUser) => ({
    path: `/api/tasks?status=${status}&dueDate=${dueDate}&assignedUser=${assignedUser}`,
    method: "GET",
  }),
  setFilterOptions: { path: "/api/filter/options", method: "POST" },
  clearFilter: { path: "/api/filter/clear", method: "POST" },
  applyFilter: { path: "/api/filter/apply", method: "POST" },
  updateFilterOptions: { path: "/api/filter/update-options", method: "PUT" },
  getFilterOptions: { path: "/api/filter/get-options", method: "GET" },
  saveFilterOptions: { path: "/api/filter/save-options", method: "POST" },
  deleteFilterOptions: { path: "/api/filter/delete-options", method: "DELETE" },
  getFilteredData: { path: "/api/filter/data", method: "GET" },
  addFilterCriteria: { path: "/api/filter/add-criteria", method: "POST" },
  removeFilterCriteria: { path: "/api/filter/remove-criteria", method: "DELETE" },
  setSortOptions: { path: "/api/sort/options", method: "POST" },
  applySort: { path: "/api/sort/apply", method: "POST" },
  updateSortOptions: { path: "/api/sort/update-options", method: "PUT" },
  getSortOptions: { path: "/api/sort/get-options", method: "GET" },
  saveSortOptions: { path: "/api/sort/save-options", method: "POST" },
  deleteSortOptions: { path: "/api/sort/delete-options", method: "DELETE" },
  getFilteredAndSortedData: { path: "/api/filter-sort/data", method: "GET" },
  resetFilterAndSort: { path: "/api/filter-sort/reset", method: "POST" },
  applyPagination: { path: "/api/pagination/apply", method: "POST" },
  updatePaginationOptions: { path: "/api/pagination/update-options", method: "PUT" },
  markInProgress: (taskId) => ({ path: `/api/tasks/${taskId}/mark-in-progress`, method: "POST" }),
};
