import React from "react"
import { UnifiedMetaDataOptions } from "./configs/database/MetaDataOptions";
import { Data } from "./components/models/data/Data";
import {  EventManager } from "./components/projects/DataAnalysisPhase/DataProcessing/DataStore";
import { Snapshot } from "@/app/components/snapshots/LocalStorageSnapshotStore";

export const defaultMetadata: UnifiedMetaDataOptions = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  projectId: 0,
  structuredMetadata: {
    metadataEntries: {},
    id: "",
    apiEndpoint: "",
    apiKey: undefined,
    timeout: 0,
    retryAttempts: 0,
    name: "",
    category: "",
    timestamp: undefined,
    createdBy: "",
    tags: [],
    metadata: {},
    initialState: undefined,
    meta: new Map<string, Snapshot<Data<any>, K>>(), // Initialize as an empty Map
    events: {} as EventManager<Data<any>,K>, // Use a default instance
 
  },
  metadataEntries: {},
  id: "",
  apiEndpoint: "",
  apiKey: undefined,
  timeout: 0,
  retryAttempts: 0,
  name: "",
  category: "",
  timestamp: undefined,
  createdBy: "",
  tags: [],
  metadata: {},
  initialState: undefined,
  meta: new Map<string, Snapshot<Data<any>, UnifiedMetaDataOptions<Data<any>, Data<any>>, Data<any>>>(), // Initialize as an empty Map
  events: {} as EventManager<Data<any>, UnifiedMetaDataOptions<Data<any>, Data<any>>, Data<any>>, // Use a default instance
  
  startDate: undefined,
  endDate: undefined,
  budget: 0,
  status: "",
  teamMembers: [],
  tasks: [],
  milestones: [],
  videos: []
};export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
