// clientConfig.ts
import { ClientEndpoints } from '@/core/typings/categories/ClientEndpoints';

export const clientConfig: ClientEndpoints = {
  fetchClientDetails: (clientId: number) => ({ path: `/api/client/${clientId}`, method: "GET" }),
  updateClientDetails: (clientId: number) => ({ path: `/api/client/${clientId}/update`, method: "PUT" }),
  connectWithTenant: (tenantId: number) => ({ path: `/api/client/connect/${tenantId}`, method: "POST" }),
  sendMessageToTenant: (tenantId: number) => ({ path: `/api/client/message/${tenantId}`, method: "POST" }),
  listConnectedTenants: { path: "/api/client/connected-tenants", method: "GET" },
  listMessages: { path: "/api/client/messages", method: "GET" },
  createTask: { path: "/api/client/tasks/create", method: "POST" },
  listTasks: { path: "/api/client/tasks", method: "GET" },
  submitProjectProposal: { path: "/api/client/projects/submit-proposal", method: "POST" },
  participateInCommunityChallenges: { path: "/api/client/community/challenges/participate", method: "POST" },
  listRewards: { path: "/api/client/rewards", method: "GET" },
  listFiles: { path: "/api/client/files", method: "GET" },
  fetchFiles: { path: "/api/client/fetchFiles", method: "GET" },
  uploadFile: { path: "/api/client/uploadFile", method: "POST" },
  batchRemoveFiles: { path: "/api/client/batchRemoveFiles", method: "POST" },
  markFileAsComplete: { path: "/api/client/markFileAsComplete", method: "POST" },
  startCollaborativeEdit: { path: "/api/client/startCollaborativeEdit", method: "POST" },
  createFileVersion: { path: "/api/client/createFileVersion", method: "POST" },
  fetchFileVersions: { path: "/api/client/fetchFileVersions", method: "GET" },
  shareFile: { path: "/api/client/shareFile", method: "POST" },
  requestAccessToFile: { path: "/api/client/requestAccessToFile", method: "POST" },
  receiveFileUpdate: { path: "/api/client/receiveFileUpdate", method: "POST" },
  exportFile: { path: "/api/client/exportFile", method: "POST" },
  archiveFile: { path: "/api/client/archiveFile", method: "POST" },
  determineFileType: { path: "/api/client/determineFileType", method: "POST" },
  importFile: { path: "/api/client/importFile", method: "POST" },
};