createMergedEndpoints.ts

import { EndpointConfigurations } from '@/core/config/EndpointConfig';
import mergeConfigurations from '@/utils/mergeConfigurations';
import { generateEndpointUrl } from '@/utils/urlGenerator';
Import ALL your configs (you already have these in endpointConfigurations.ts)
import {
    analyticsConfig,
    apiEndpointConfig,
    apiWebBaseConfig,
    authConfig,
    batchConfig,
    blogsConfig,
    calendarConfig,
    categoryConfig,
    chatConfig,
    clientConfig,
    collaborationToolsConfig,
    commentsConfig,
    communicationConfig,
    communityInteractionConfig,
    contentConfig,
    cryptoConfig,
    dataAnalysisConfig,
    dataConfig,
    dataProvidersConfig,
    databaseConfig,
    delegatesConfig,
    detailsConfig,
    devConfig,
    dexConfig,
    documentsConfig,
    donationsConfig,
    drawingConfig,
    externalAuthConfig,
    feedbackConfig,
    filesConfig,
    filteringConfig,
    freelancersConfig,
    generatorsConfig,
    globalCollaborationConfig,
    highlightsConfig,
    loggingConfig,
    logsConfig,
    markerConfig,
    messagesConfig,
    moderatorsConfig,
    monetizationConfig,
    newsConfig,
    notesConfig,
    parameterCustomizationConfig,
    participantsConfig,
    paymentConfig,
    personasConfig,
    phasesConfig,
    projectManagementConfig,
    projectOwnerConfig,
    projectsConfig,
    randomWalkConfig,
    realtimeConfig,
    registrationConfig,
    reportsConfig,
    screenSharingConfig,
    searchingConfig,
    securityConfig,
    snapshotsConfig,
    sortingConfig,
    stateGovCitiesConfig,
    tasksConfig,
    teamManagementConfig,
    teamsConfig,
    themeConfig,
    todosConfig,
    toolbarConfig,
    tradingConfig,
    uiConfig,
    uiSettingsConfig,
    userManagementConfig,
    userRolesConfig,
    userRolesNFTConfig,
    userSettingsConfig,
    usersConfig,
    versionConfig,
    videosConfig,
    webConfig,
} from '@/core/api/endpointConfigurations';

Define which configs to use for dynamic mapping
Create dynamicConfigMap directly from endpointConfigurations
const dynamicConfigMap = {
  apiWebBase: apiWebBaseConfig,
  apiConfig: apiEndpointConfig,
  analytics: analyticsConfig,
  auth: authConfig,
  batch: batchConfig,
  blogs: blogsConfig,
  calendar: calendarConfig,
  categories: categoryConfig,
  categoriesEndpoints: categoryConfig,
  chat: chatConfig,
  client: clientConfig,
  collaborationTools: collaborationToolsConfig,
  comments: commentsConfig,
  communication: communicationConfig,
  communityInteraction: communityInteractionConfig,
  content: contentConfig,
  crypto: cryptoConfig,
  data: dataConfig,
  database: databaseConfig,
  dataAnalysis: dataAnalysisConfig,
  dataProviders: dataProvidersConfig,
  delegates: delegatesConfig,
  details: detailsConfig,
  dev: devConfig,
  dex: dexConfig,
  documents: documentsConfig,
  donations: donationsConfig,
  drawing: drawingConfig,
  externalAuth: externalAuthConfig,
  feedback: feedbackConfig,
  files: filesConfig,
  filtering: filteringConfig,
  freelancers: freelancersConfig,
  generators: generatorsConfig,
  globalCollaboration: globalCollaborationConfig,
  highlights: highlightsConfig,
  logging: loggingConfig,
  marker: markerConfig,
  messages: messagesConfig,
  moderators: moderatorsConfig,
  monetization: monetizationConfig,
  news: newsConfig,
  notes: notesConfig,
  payment: paymentConfig,
  parameterCustomization: parameterCustomizationConfig,
  participants: participantsConfig,
  personas: personasConfig,
  projects: projectsConfig,
  phases: phasesConfig,
  projectManagement: projectManagementConfig,
  projectOwner: projectOwnerConfig,
  randomWalk: randomWalkConfig,
  registration: registrationConfig,
  reports: reportsConfig,
  security: securityConfig,
  stateGovCities: stateGovCitiesConfig,
  sorting: sortingConfig,
  searching: searchingConfig,
  snapshots: snapshotsConfig,
  realtime: realtimeConfig,
  tasks: tasksConfig,
  teams: teamsConfig,
  teamManagement: teamManagementConfig,
  theme: themeConfig,
  toolbar: toolbarConfig,
  trading: tradingConfig,
  todos: todosConfig,
  ui: uiConfig,
  userManagement: userManagementConfig,
  userRoles: userRolesConfig,
  userRolesNFT: userRolesNFTConfig,
  userSettings: userSettingsConfig,
  videos: videosConfig,
  users: usersConfig,
  version: versionConfig,
  web: webConfig,
  screenSharing: screenSharingConfig,
  logs: logsConfig,
  uiSettings: uiSettingsConfig,
};

export const createMergedEndpoints = (): EndpointConfigurations => ({
  analytics: analyticsConfig,
  apiConfig: apiEndpointConfig,
  apiWebBase: apiWebBaseConfig,
  auth: authConfig,
  batch: batchConfig,
  blogs: blogsConfig,
  calendar: calendarConfig,
  categories: categoryConfig,
  categoriesEndpoints: categoryConfig,
  chat: chatConfig,
  client: clientConfig,
  collaborationTools: collaborationToolsConfig,
  comments: commentsConfig,
  communication: communicationConfig,
  communityInteraction: communityInteractionConfig,
  content: contentConfig,
  crypto: cryptoConfig,
  data: dataConfig,
  database: databaseConfig,
  dataAnalysis: dataAnalysisConfig,
  dataProviders: dataProvidersConfig,
  delegates: delegatesConfig,
  details: detailsConfig,
  dev: devConfig,
  dex: dexConfig,
  documents: documentsConfig,
  donations: donationsConfig,
  drawing: drawingConfig,
  externalAuth: externalAuthConfig,
  feedback: feedbackConfig,
  files: filesConfig,
  filtering: filteringConfig,
  freelancers: freelancersConfig,
  generators: generatorsConfig,
  globalCollaboration: globalCollaborationConfig,
  highlights: highlightsConfig,
  logging: loggingConfig,
  logs: logsConfig,
  marker: markerConfig,
  messages: messagesConfig,
  moderators: moderatorsConfig,
  monetization: monetizationConfig,
  news: newsConfig,
  notes: notesConfig,
  parameterCustomization: parameterCustomizationConfig,
  participants: participantsConfig,
  payment: paymentConfig,
  personas: personasConfig,
  phases: phasesConfig,
  projectManagement: projectManagementConfig,
  projectOwner: projectOwnerConfig,
  projects: projectsConfig,
  randomWalk: randomWalkConfig,
  realtime: realtimeConfig,
  registration: registrationConfig,
  reports: reportsConfig,
  screenSharing: screenSharingConfig,
  searching: searchingConfig,
  security: securityConfig,
  snapshots: snapshotsConfig,
  sorting: sortingConfig,
  stateGovCities: stateGovCitiesConfig,
  tasks: tasksConfig,
  teamManagement: teamManagementConfig,
  teams: teamsConfig,
  theme: themeConfig,
  toolbar: toolbarConfig,
  todos: todosConfig,
  trading: tradingConfig,
  ui: uiConfig,
  uiSettings: uiSettingsConfig,
  userManagement: userManagementConfig,
  userRoles: userRolesConfig,
  userRolesNFT: userRolesNFTConfig,
  users: usersConfig,
  userSettings: userSettingsConfig,
  version: versionConfig,
  videos: videosConfig,
  web: webConfig,
});


Helper function for complex categories (keep your existing manual mappings)
const getManualComplexMapping = (category: string, endpointConfigurations: EndpointConfigurations) => {
  switch (category) {
    case 'client':
      return mergeConfigurations(endpointConfigurations.client, {
        fetchClientDetails: (clientId: number) => generateEndpointUrl("client", "fetchClientDetails", { clientId }),
        updateClientDetails: (clientId: number) => generateEndpointUrl("client", "updateClientDetails", { clientId }),
        connectWithTenant: (tenantId: number) => generateEndpointUrl("client", "connectWithTenant", { tenantId }),
        sendMessageToTenant: (tenantId: number) => generateEndpointUrl("client", "sendMessageToTenant", { tenantId }),
        listConnectedTenants: generateEndpointUrl("client", "listConnectedTenants"),
        listMessages: generateEndpointUrl("client", "listMessages"),
        createTask: generateEndpointUrl("client", "createTask"),
        listTasks: generateEndpointUrl("client", "listTasks"),
        submitProjectProposal: generateEndpointUrl("client", "submitProjectProposal"),
        participateInCommunityChallenges: generateEndpointUrl("client", "participateInCommunityChallenges"),
        listRewards: generateEndpointUrl("client", "listRewards"),
        listFiles: generateEndpointUrl("client", "listFiles"),
        fetchFiles: generateEndpointUrl("client", "fetchFiles"),
        uploadFile: generateEndpointUrl("client", "uploadFile"),
        batchRemoveFiles: generateEndpointUrl("client", "batchRemoveFiles"),
        markFileAsComplete: generateEndpointUrl("client", "markFileAsComplete"),
        startCollaborativeEdit: generateEndpointUrl("client", "startCollaborativeEdit"),
        createFileVersion: generateEndpointUrl("client", "createFileVersion"),
        fetchFileVersions: generateEndpointUrl("client", "fetchFileVersions"),
        shareFile: generateEndpointUrl("client", "shareFile"),
        requestAccessToFile: generateEndpointUrl("client", "requestAccessToFile"),
        receiveFileUpdate: generateEndpointUrl("client", "receiveFileUpdate"),
        exportFile: generateEndpointUrl("client", "exportFile"),
        archiveFile: generateEndpointUrl("client", "archiveFile"),
        determineFileType: generateEndpointUrl("client", "determineFileType"),
        importFile: generateEndpointUrl("client", "importFile"),
      });

    case 'content':
      return mergeConfigurations(endpointConfigurations.content, {
        create: generateEndpointUrl("content", "create"),
        update: (contentId: number) => generateEndpointUrl("content", "update", { contentId }),
        delete: (contentId: number) => generateEndpointUrl("content", "delete", { contentId }),
        fetch: generateEndpointUrl("content", "fetch"),
        add: generateEndpointUrl("content", "add"),
        remove: (contentId: number) => generateEndpointUrl("content", "remove", { contentId }),
        fetchAll: generateEndpointUrl("content", "fetchAll"),
        fetchAllByType: (contentType: string) => generateEndpointUrl("content", "fetchAllByType", { contentType }),
        fetchAllByTypeAndTeam: (contentType: string, teamId: number) => generateEndpointUrl("content", "fetchAllByTypeAndTeam", { contentType, teamId }),
        fetchAllByTeam: (teamId: number) => generateEndpointUrl("content", "fetchAllByTeam", { teamId }),
      });

    case 'delegates':
      return mergeConfigurations(endpointConfigurations.delegates, {
        create: generateEndpointUrl("delegates", "create"),
        list: generateEndpointUrl("delegates", "list"),
        single: (delegateId: number) => generateEndpointUrl("delegates", "single", { delegateId }),
        add: generateEndpointUrl("delegates", "add"),
        remove: (delegateId: number) => generateEndpointUrl("delegates", "remove", { delegateId }),
        update: (delegateId: number) => generateEndpointUrl("delegates", "update", { delegateId }),
      });

    case 'documents':
      return mergeConfigurations(endpointConfigurations.documents, {
        list: generateEndpointUrl("documents", "list"),
        single: (documentId: string) => generateEndpointUrl("documents", `single/${documentId}`),
        add: generateEndpointUrl("documents", "add"),
        remove: (documentId: string) => generateEndpointUrl("documents", `remove/${documentId}`),
        update: (documentId: string) => generateEndpointUrl("documents", `update/${documentId}`),
        download: (documentId: string) => generateEndpointUrl("documents", `download/${documentId}`),
        search: generateEndpointUrl("documents", "search"),
        filter: generateEndpointUrl("documents", "filter"),
        upload: generateEndpointUrl("documents", "upload"),
        share: generateEndpointUrl("documents", "share"),
        lock: generateEndpointUrl("documents", "lock"),
        unlock: generateEndpointUrl("documents", "unlock"),
        archive: generateEndpointUrl("documents", "archive"),
        restore: generateEndpointUrl("documents", "restore"),
        move: generateEndpointUrl("documents", "move"),
        copy: generateEndpointUrl("documents", "copy"),
        rename: generateEndpointUrl("documents", "rename"),
        changePermissions: generateEndpointUrl("documents", "changePermissions"),
        merge: generateEndpointUrl("documents", "merge"),
        split: generateEndpointUrl("documents", "split"),
        validate: generateEndpointUrl("documents", "validate"),
        encrypt: generateEndpointUrl("documents", "encrypt"),
        decrypt: generateEndpointUrl("documents", "decrypt"),
        trackChanges: generateEndpointUrl("documents", "trackChanges"),
        compare: generateEndpointUrl("documents", "compare"),
        tag: generateEndpointUrl("documents", "tag"),
        categorize: generateEndpointUrl("documents", "categorize"),
        customizeView: generateEndpointUrl("documents", "customizeView"),
        comment: generateEndpointUrl("documents", "comment"),
        mentionUser: generateEndpointUrl("documents", "mentionUser"),
        assignTask: generateEndpointUrl("documents", "assignTask"),
        requestReview: generateEndpointUrl("documents", "requestReview"),
        approve: generateEndpointUrl("documents", "approve"),
        reject: generateEndpointUrl("documents", "reject"),
        requestFeedback: generateEndpointUrl("documents", "requestFeedback"),
        provideFeedback: generateEndpointUrl("documents", "provideFeedback"),
        resolveFeedback: generateEndpointUrl("documents", "resolveFeedback"),
        collaborativeEditing: generateEndpointUrl("documents", "collaborativeEditing"),
        smartTagging: generateEndpointUrl("documents", "smartTagging"),
        annotation: generateEndpointUrl("documents", "annotation"),
        activityLogging: generateEndpointUrl("documents", "activityLogging"),
        intelligentSearch: generateEndpointUrl("documents", "intelligentSearch"),
        createVersion: generateEndpointUrl("documents", "createVersion"),
        revertVersion: generateEndpointUrl("documents", "revertVersion"),
        viewHistory: generateEndpointUrl("documents", "viewHistory"),
        compareVersions: generateEndpointUrl("documents", "compareVersions"),
        grantAccess: generateEndpointUrl("documents", "grantAccess"),
        revokeAccess: generateEndpointUrl("documents", "revokeAccess"),
        managePermissions: generateEndpointUrl("documents", "managePermissions"),
        initiateWorkflow: generateEndpointUrl("documents", "initiateWorkflow"),
        automateTasks: generateEndpointUrl("documents", "automateTasks"),
        triggerEvents: generateEndpointUrl("documents", "triggerEvents"),
        approvalWorkflow: generateEndpointUrl("documents", "approvalWorkflow"),
        lifecycleManagement: generateEndpointUrl("documents", "lifecycleManagement"),
        connectExternalSystem: generateEndpointUrl("documents", "connectExternalSystem"),
        synchronizeStorage: generateEndpointUrl("documents", "synchronizeStorage"),
        importFromExternal: generateEndpointUrl("documents", "importFromExternal"),
        exportToExternal: generateEndpointUrl("documents", "exportToExternal"),
        generateReport: generateEndpointUrl("documents", "generateReport"),
        exportReport: generateEndpointUrl("documents", "exportReport"),
        scheduleReport: generateEndpointUrl("documents", "scheduleReport"),
        customizeReport: generateEndpointUrl("documents", "customizeReport"),
        manageSubscriptions: generateEndpointUrl("documents", "manageSubscriptions"),
        handleSubscriptions: generateEndpointUrl("documents", "handleSubscriptions"),
        notificationSettings: generateEndpointUrl("documents", "notificationSettings"),
        notifyChanges: generateEndpointUrl("documents", "notifyChanges"),
        backup: generateEndpointUrl("documents", "backup"),
        retrieveBackup: generateEndpointUrl("documents", "retrieveBackup"),
        redact: generateEndpointUrl("documents", "redact"),
        accessControls: generateEndpointUrl("documents", "accessControls"),
        templates: generateEndpointUrl("documents", "templates"),
      });

    case 'notes':
      return mergeConfigurations(endpointConfigurations.notes, {
        // Core CRUD operations
        list: generateEndpointUrl("notes", "list"),
        single: (noteId: number) => generateEndpointUrl("notes", "single"),
        create: generateEndpointUrl("notes", "create"),
        update: (noteId: number) => generateEndpointUrl("notes", "update"),
        delete: (noteId: number) => generateEndpointUrl("notes", "delete"),
        
        // State management
        archive: (noteId: number) => generateEndpointUrl("notes", "archive"),
        restore: (noteId: number) => generateEndpointUrl("notes", "restore"),
        move: (noteId: number) => generateEndpointUrl("notes", "move"),
        pin: (noteId: number) => generateEndpointUrl("notes", "pin"),
        unpin: (noteId: number) => generateEndpointUrl("notes", "unpin"),
        duplicate: (noteId: number) => generateEndpointUrl("notes", "duplicate"),
        
        // Content operations
        merge: generateEndpointUrl("notes", "merge"),
        split: (noteId: number) => generateEndpointUrl("notes", "split"),
        
        // Search and filter
        search: generateEndpointUrl("notes", "search"),
        filter: generateEndpointUrl("notes", "filter"),
        
        // Bulk operations
        bulkUpdate: generateEndpointUrl("notes", "bulkUpdate"),
        bulkDelete: generateEndpointUrl("notes", "bulkDelete"),
        
        // Import/Export
        export: generateEndpointUrl("notes", "export"),
        import: generateEndpointUrl("notes", "import"),
        
        // Tag management
        tags: (noteId: number) => generateEndpointUrl("notes", "tags"),
        addTag: (noteId: number) => generateEndpointUrl("notes", "addTag"),
        removeTag: (noteId: number, tagId: number) => generateEndpointUrl("notes", "removeTag"),
        
        // Attachment management
        attachments: (noteId: number) => generateEndpointUrl("notes", "attachments"),
        addAttachment: (noteId: number) => generateEndpointUrl("notes", "addAttachment"),
        removeAttachment: (noteId: number, attachmentId: number) => generateEndpointUrl("notes", "removeAttachment"),
        
        // Version management
        versions: (noteId: number) => generateEndpointUrl("notes", "versions"),
        restoreVersion: (noteId: number, versionId: number) => generateEndpointUrl("notes", "restoreVersion"),
        
        // Collaboration
        share: (noteId: number) => generateEndpointUrl("notes", "share"),
        unshare: (noteId: number) => generateEndpointUrl("notes", "unshare"),
        collaborators: (noteId: number) => generateEndpointUrl("notes", "collaborators"),
        addCollaborator: (noteId: number) => generateEndpointUrl("notes", "addCollaborator"),
        removeCollaborator: (noteId: number, collaboratorId: number) => generateEndpointUrl("notes", "removeCollaborator"),
        
        // Comments
        comments: (noteId: number) => generateEndpointUrl("notes", "comments"),
        addComment: (noteId: number) => generateEndpointUrl("notes", "addComment"),
        updateComment: (noteId: number, commentId: number) => generateEndpointUrl("notes", "updateComment"),
        deleteComment: (noteId: number, commentId: number) => generateEndpointUrl("notes", "deleteComment"),
        
        // Analytics
        analytics: (noteId: number) => generateEndpointUrl("notes", "analytics"),
        
        // Templates
        templates: generateEndpointUrl("notes", "templates"),
        createFromTemplate: (templateId: number) => generateEndpointUrl("notes", "createFromTemplate"),
      });

    case 'realtime':
      return mergeConfigurations(endpointConfigurations.realtime, {
        list: generateEndpointUrl("realtime", "list"),
        single: (realtimeId: number) => generateEndpointUrl("realtime", `single/${realtimeId}`),
        add: generateEndpointUrl("realtime", "add"),
        remove: (realtimeId: number) => generateEndpointUrl("realtime", `remove/${realtimeId}`),
        update: (realtimeId: number) => generateEndpointUrl("realtime", `update/${realtimeId}`),
        updateList: generateEndpointUrl("realtime", "updateList"),
        search: generateEndpointUrl("realtime", "search"),
        updateRole: (realtimeId: number) => generateEndpointUrl("realtime", `updateRole/${realtimeId}`),
        updateRoles: generateEndpointUrl("realtime", "updateRoles"),
        fetch: generateEndpointUrl("realtime", "fetch"),
        create: generateEndpointUrl("realtime", "create"),
        delete: (realtimeId: number) => generateEndpointUrl("realtime", `delete/${realtimeId}`),
        fetchById: (realtimeId: number) => generateEndpointUrl("realtime", `fetchById/${realtimeId}`),
        connect: generateEndpointUrl("realtime", "connect"),
        disconnect: generateEndpointUrl("realtime", "disconnect"),
        sendMessage: generateEndpointUrl("realtime", "sendMessage"),
        fetchMessages: generateEndpointUrl("realtime", "fetchMessages"),
      });

    case 'snapshots':
      return mergeConfigurations(endpointConfigurations.snapshots, {
        list: generateEndpointUrl("snapshots", "list"),
        create: generateEndpointUrl("snapshots", "create"),
        single: (snapshotId: string) => generateEndpointUrl("snapshots", "single", { snapshotId }),
        add: generateEndpointUrl("snapshots", "add"),
        remove: (snapshotId: string) => generateEndpointUrl("snapshots", "remove", { snapshotId }),
        update: (snapshotId: string) => generateEndpointUrl("snapshots", "update", { snapshotId }),
        fetchUpdatedData: (snapshotId: string) => generateEndpointUrl("snapshots", "fetchUpdatedData", { snapshotId }),
        bulkAdd: generateEndpointUrl("snapshots", "bulkAdd"),
        bulkRemove: generateEndpointUrl("snapshots", "bulkRemove"),
        bulkUpdate: generateEndpointUrl("snapshots", "bulkUpdate"),
      });

    case 'teams':
      return mergeConfigurations(endpointConfigurations.teams, {
        list: generateEndpointUrl("teams", "list"),
        single: (teamId: number) => generateEndpointUrl("teams", "single", teamId),
        add: generateEndpointUrl("teams", "add"),
        fetchTeamData: (teamId: number) => generateEndpointUrl("teams", "fetchTeamData", teamId),
        remove: (teamId: number) => generateEndpointUrl("teams", "remove", teamId),
        update: (teamId: number) => generateEndpointUrl("teams", "update", teamId),
        updateTeams: (teamIds: number[]) => generateEndpointUrl("teams", "updateTeams", teamIds),
      });

    case 'todos':
      return mergeConfigurations(endpointConfigurations.todos, {
        create: generateEndpointUrl("todos", "create"),
        update: (todoId: number) => generateEndpointUrl("todos", "update", { todoId }),
        delete: (todoId: number) => generateEndpointUrl("todos", "delete", { todoId }),
        complete: (todoId: number) => generateEndpointUrl("todos", "complete", { todoId }),
        uncomplete: (todoId: number) => generateEndpointUrl("todos", "uncomplete", { todoId }),
        fetch: generateEndpointUrl("todos", "fetch"),
        assign: (todoId: number, teamId: number) => generateEndpointUrl("todos", "assign", { todoId, teamId }),
        reassign: (todoId: number, newTeamId: number) => generateEndpointUrl("todos", "reassign", { todoId, newTeamId }),
        unassign: (todoId: number) => generateEndpointUrl("todos", "unassign", { todoId }),
        toggle: (entityId: number, entityType: string) => generateEndpointUrl("todos", "toggle", { entityId, entityType }),
        search: generateEndpointUrl("todos", "search"),
        bulkAssign: generateEndpointUrl("todos", "bulkAssign"),
        bulkUnassign: generateEndpointUrl("todos", "bulkUnassign"),
      });

    case 'ui':
      return mergeConfigurations(endpointConfigurations.ui, {
        userData: (userId: string) => generateEndpointUrl("ui", "userData", { userId }),
        userSettings: (userId: string) => generateEndpointUrl("ui", "userSettings", { userId }),
        updateUserSettings: (userId: string) => generateEndpointUrl("ui", "updateUserSettings", { userId }),
        userDashboard: (userId: string) => generateEndpointUrl("ui", "userDashboard", { userId }),
        updateDashboardLayout: (userId: string) => generateEndpointUrl("ui", "updateDashboardLayout", { userId }),
        userWidgets: (userId: string) => generateEndpointUrl("ui", "userWidgets", { userId }),
        customizeWidget: (userId: string, widgetId: string) => generateEndpointUrl("ui", "customizeWidget", { userId, widgetId }),
        userThemes: generateEndpointUrl("ui", "userThemes"),
        switchTheme: (userId: string) => generateEndpointUrl("ui", "switchTheme", { userId }),
        userPreferences: (userId: string) => generateEndpointUrl("ui", "userPreferences", { userId }),
        updateUserPreferences: (userId: string) => generateEndpointUrl("ui", "updateUserPreferences", { userId }),
        userNotifications: (userId: string) => generateEndpointUrl("ui", "userNotifications", { userId }),
        markNotificationRead: (userId: string, notificationId: string) => generateEndpointUrl("ui", "markNotificationRead", { userId, notificationId }),
        clearAllNotifications: (userId: string) => generateEndpointUrl("ui", "clearAllNotifications", { userId }),
        userMessages: (userId: string) => generateEndpointUrl("ui", "userMessages", { userId }),
        sendMessage: (userId: string) => generateEndpointUrl("ui", "sendMessage", { userId }),
        toggleDarkMode: (userId: string) => generateEndpointUrl("ui", "toggleDarkMode", { userId }),
        userAvatar: (userId: string) => generateEndpointUrl("ui", "userAvatar", { userId }),
        updateUserAvatar: (userId: string) => generateEndpointUrl("ui", "updateUserAvatar", { userId }),
        branding: generateEndpointUrl("ui", "branding"),
        interfaceContent: generateEndpointUrl("ui", "interfaceContent"),
        updateInterfaceSettings: generateEndpointUrl("ui", "updateInterfaceSettings"),
        fetchComponents: generateEndpointUrl("ui", "fetchComponents"),
        updateComponentState: (componentId: string) => generateEndpointUrl("ui", "updateComponentState", { componentId }),
        saveLayout: (userId: string) => generateEndpointUrl("ui", "saveLayout", { userId }),
        loadLayout: (userId: string) => generateEndpointUrl("ui", "loadLayout", { userId }),
        resetLayout: (userId: string) => generateEndpointUrl("ui", "resetLayout", { userId }),
      });

    case 'users':
      return mergeConfigurations(endpointConfigurations.users, {
        list: generateEndpointUrl("users", "list"),
        single: (userId: number) => generateEndpointUrl("users", "single", { userId }),
        add: generateEndpointUrl("users", "add"),
        remove: (userId: number) => generateEndpointUrl("users", "remove", { userId }),
        update: (userId: number) => generateEndpointUrl("users", "update", { userId }),
        updateList: generateEndpointUrl("users", "updateList"),
        search: generateEndpointUrl("users", "search"),
        updateRole: (userId: number) => generateEndpointUrl("users", "updateRole", { userId }),
        updateRoles: (userIds: number[]) => generateEndpointUrl("users", "updateRoles", { userIds }),
      });

    default:
      // Fallback to dynamic for any complex category not explicitly handled
      return mergeConfigurations(
        endpointConfigurations[category as keyof EndpointConfigurations],
        Object.fromEntries(
          Object.keys(dynamicConfigMap[category as keyof typeof dynamicConfigMap]).map(key => [
            key,
            generateEndpointUrl(category as keyof EndpointConfigurations, key)
          ])
        )
      );
  }
};