// documentsConfig.ts
documentConfig.ts
import { BASE_URL } from '@/core/api/baseUrl';
import { DocumentEndpoints } from '@/core/typings/categories/DocumentEndpoints';

export const documentsConfig: DocumentEndpoints = {
  list: { path: `${BASE_URL}/api/documents`, method: "GET" },
  single: (documentId: string) => ({ path: `${BASE_URL}/api/documents/${documentId}`, method: "GET" }),
  add: { path: `${BASE_URL}/api/documents`, method: "POST" },
  remove: (documentId: string) => ({ path: `${BASE_URL}/api/documents/${documentId}`, method: "DELETE" }),
  update: (documentId: string) => ({ path: `${BASE_URL}/api/documents/${documentId}`, method: "PUT" }),
  download: (documentId: string) => ({ path: `${BASE_URL}/api/documents/downloadDocument/${documentId}`, method: "GET" }),
  search: { path: `${BASE_URL}/api/documents/search`, method: "POST" },
  filter: { path: `${BASE_URL}/api/documents/filter`, method: "POST" },
  upload: { path: `${BASE_URL}/api/documents/upload`, method: "POST" },
  share: { path: `${BASE_URL}/api/documents/share`, method: "POST" },
  lock: { path: `${BASE_URL}/api/documents/lock`, method: "POST" },
  unlock: { path: `${BASE_URL}/api/documents/unlock`, method: "POST" },
  archive: { path: `${BASE_URL}/api/documents/archive`, method: "POST" },
  restore: { path: `${BASE_URL}/api/documents/restore`, method: "POST" },
  move: { path: `${BASE_URL}/api/documents/move`, method: "POST" },
  copy: { path: `${BASE_URL}/api/documents/copy`, method: "POST" },
  rename: { path: `${BASE_URL}/api/documents/rename`, method: "PUT" },
  changePermissions: { path: `${BASE_URL}/api/documents/changePermissions`, method: "POST" },
  merge: { path: `${BASE_URL}/api/documents/merge`, method: "POST" },
  split: { path: `${BASE_URL}/api/documents/split`, method: "POST" },
  validate: { path: `${BASE_URL}/api/documents/validate`, method: "POST" },
  encrypt: { path: `${BASE_URL}/api/documents/encrypt`, method: "POST" },
  decrypt: { path: `${BASE_URL}/api/documents/decrypt`, method: "POST" },
  trackChanges: { path: `${BASE_URL}/api/documents/trackChanges`, method: "POST" },
  compare: { path: `${BASE_URL}/api/documents/compare`, method: "POST" },
  tag: { path: `${BASE_URL}/api/documents/tag`, method: "POST" },
  categorize: { path: `${BASE_URL}/api/documents/categorize`, method: "POST" },
  customizeView: { path: `${BASE_URL}/api/documents/customizeView`, method: "POST" },
  comment: { path: `${BASE_URL}/api/documents/comment`, method: "POST" },
  mentionUser: { path: `${BASE_URL}/api/documents/mentionUser`, method: "POST" },
  assignTask: { path: `${BASE_URL}/api/documents/assignTask`, method: "POST" },
  requestReview: { path: `${BASE_URL}/api/documents/requestReview`, method: "POST" },
  approve: { path: `${BASE_URL}/api/documents/approve`, method: "POST" },
  reject: { path: `${BASE_URL}/api/documents/reject`, method: "POST" },
  requestFeedback: { path: `${BASE_URL}/api/documents/requestFeedback`, method: "POST" },
  provideFeedback: { path: `${BASE_URL}/api/documents/provideFeedback`, method: "POST" },
  resolveFeedback: { path: `${BASE_URL}/api/documents/resolveFeedback`, method: "POST" },
  collaborativeEditing: { path: `${BASE_URL}/api/documents/collaborativeEditing`, method: "POST" },
  smartTagging: { path: `${BASE_URL}/api/documents/smartTagging`, method: "POST" },
  annotation: { path: `${BASE_URL}/api/documents/annotation`, method: "POST" },
  activityLogging: { path: `${BASE_URL}/api/documents/activityLogging`, method: "POST" },
  intelligentSearch: { path: `${BASE_URL}/api/documents/intelligentSearch`, method: "POST" },
  createVersion: { path: `${BASE_URL}/api/documents/createVersion`, method: "POST" },
  revertVersion: { path: `${BASE_URL}/api/documents/revertVersion`, method: "POST" },
  viewHistory: { path: `${BASE_URL}/api/documents/viewHistory`, method: "GET" },
  compareVersions: { path: `${BASE_URL}/api/documents/compareVersions`, method: "POST" },
  grantAccess: { path: `${BASE_URL}/api/documents/grantAccess`, method: "POST" },
  revokeAccess: { path: `${BASE_URL}/api/documents/revokeAccess`, method: "POST" },
  managePermissions: { path: `${BASE_URL}/api/documents/managePermissions`, method: "POST" },
  initiateWorkflow: { path: `${BASE_URL}/api/documents/initiateWorkflow`, method: "POST" },
  automateTasks: { path: `${BASE_URL}/api/documents/automateTasks`, method: "POST" },
  triggerEvents: { path: `${BASE_URL}/api/documents/triggerEvents`, method: "POST" },
  approvalWorkflow: { path: `${BASE_URL}/api/documents/approvalWorkflow`, method: "POST" },
  lifecycleManagement: { path: `${BASE_URL}/api/documents/lifecycleManagement`, method: "POST" },
  connectExternalSystem: { path: `${BASE_URL}/api/documents/connectExternalSystem`, method: "POST" },
  synchronizeStorage: { path: `${BASE_URL}/api/documents/synchronizeStorage`, method: "POST" },
  importFromExternal: { path: `${BASE_URL}/api/documents/importFromExternal`, method: "POST" },
  exportToExternal: { path: `${BASE_URL}/api/documents/exportToExternal`, method: "POST" },
  generateReport: { path: `${BASE_URL}/api/documents/generateReport`, method: "POST" },
  exportReport: { path: `${BASE_URL}/api/documents/exportReport`, method: "POST" },
  scheduleReport: { path: `${BASE_URL}/api/documents/scheduleReport`, method: "POST" },
  customizeReport: { path: `${BASE_URL}/api/documents/customizeReport`, method: "POST" },
  // Add the missing endpoints here too:
  manageSubscriptions: { path: `${BASE_URL}/api/documents/manageSubscriptions`, method: "POST" },
  handleSubscriptions: { path: `${BASE_URL}/api/documents/handleSubscriptions`, method: "POST" },
  notificationSettings: { path: `${BASE_URL}/api/documents/notificationSettings`, method: "POST" },
  notifyChanges: { path: `${BASE_URL}/api/documents/notifyChanges`, method: "POST" },
  backup: { path: `${BASE_URL}/api/documents/backup`, method: "POST" },
  retrieveBackup: { path: `${BASE_URL}/api/documents/retrieveBackup`, method: "GET" },
  redact: { path: `${BASE_URL}/api/documents/redact`, method: "PUT" },
  accessControls: { path: `${BASE_URL}/api/documents/accessControls`, method: "POST" },
  templates: { path: `${BASE_URL}/api/documents/templates`, method: "GET" },
};

