// notesConfig.ts
import type { NotesEndpoints } from '@/core/typings/categories/NotesEndpoints';

export const notesConfig: NotesEndpoints = {
  list: { path: "/notes", method: "GET" },
  single: (noteId: number) => ({ path: `/notes/${noteId}`, method: "GET" }),
  create: { path: "/notes", method: "POST" },
  update: (noteId: number) => ({ path: `/notes/${noteId}`, method: "PUT" }),
  delete: (noteId: number) => ({ path: `/notes/${noteId}`, method: "DELETE" }),
  archive: (noteId: number) => ({ path: `/notes/${noteId}/archive`, method: "POST" }),
  restore: (noteId: number) => ({ path: `/notes/${noteId}/restore`, method: "POST" }),
  move: (noteId: number) => ({ path: `/notes/${noteId}/move`, method: "POST" }),
  merge: { path: "/notes/merge", method: "POST" },
  split: (noteId: number) => ({ path: `/notes/${noteId}/split`, method: "POST" }),
  search: { path: "/notes/search", method: "GET" },
  filter: { path: "/notes/filter", method: "GET" },
  bulkUpdate: { path: "/notes/bulk", method: "PUT" },
  bulkDelete: { path: "/notes/bulk", method: "DELETE" },
  export: { path: "/notes/export", method: "GET" },
  import: { path: "/notes/import", method: "POST" },
  tags: (noteId: number) => ({ path: `/notes/${noteId}/tags`, method: "GET" }),
  addTag: (noteId: number) => ({ path: `/notes/${noteId}/tags`, method: "POST" }),
  removeTag: (noteId: number, tagId: number) => ({ path: `/notes/${noteId}/tags/${tagId}`, method: "DELETE" }),
  attachments: (noteId: number) => ({ path: `/notes/${noteId}/attachments`, method: "GET" }),
  addAttachment: (noteId: number) => ({ path: `/notes/${noteId}/attachments`, method: "POST" }),
  removeAttachment: (noteId: number, attachmentId: number) => ({ path: `/notes/${noteId}/attachments/${attachmentId}`, method: "DELETE" }),
  versions: (noteId: number) => ({ path: `/notes/${noteId}/versions`, method: "GET" }),
  restoreVersion: (noteId: number, versionId: number) => ({ path: `/notes/${noteId}/versions/${versionId}/restore`, method: "POST" }),
  share: (noteId: number) => ({ path: `/notes/${noteId}/share`, method: "POST" }),
  unshare: (noteId: number) => ({ path: `/notes/${noteId}/share`, method: "DELETE" }),
  collaborators: (noteId: number) => ({ path: `/notes/${noteId}/collaborators`, method: "GET" }),
  addCollaborator: (noteId: number) => ({ path: `/notes/${noteId}/collaborators`, method: "POST" }),
  removeCollaborator: (noteId: number, collaboratorId: number) => ({ path: `/notes/${noteId}/collaborators/${collaboratorId}`, method: "DELETE" }),
  comments: (noteId: number) => ({ path: `/notes/${noteId}/comments`, method: "GET" }),
  addComment: (noteId: number) => ({ path: `/notes/${noteId}/comments`, method: "POST" }),
  updateComment: (noteId: number, commentId: number) => ({ path: `/notes/${noteId}/comments/${commentId}`, method: "PUT" }),
  deleteComment: (noteId: number, commentId: number) => ({ path: `/notes/${noteId}/comments/${commentId}`, method: "DELETE" }),
  analytics: (noteId: number) => ({ path: `/notes/${noteId}/analytics`, method: "GET" }),
  duplicate: (noteId: number) => ({ path: `/notes/${noteId}/duplicate`, method: "POST" }),
  pin: (noteId: number) => ({ path: `/notes/${noteId}/pin`, method: "POST" }),
  unpin: (noteId: number) => ({ path: `/notes/${noteId}/unpin`, method: "POST" }),
  templates: { path: "/notes/templates", method: "GET" },
  createFromTemplate: (templateId: number) => ({ path: `/notes/templates/${templateId}/create`, method: "POST" }),
};