// projectsConfig.ts
import { ProjectsEndpoints } from '@/core/typings/categories/ProjectsEndpoints';

export const projectsConfig: ProjectsEndpoints = {
  list: { path: "/projects", method: "GET" },
  single: (projectId) => ({ path: `/projects/${projectId}`, method: "GET" }),
  add: { path: "/projects", method: "POST" },
  remove: (projectId) => ({ path: `/projects/${projectId}`, method: "DELETE" }),
  update: (projectId) => ({ path: `/projects/${projectId}`, method: "PUT" }),

  tasks: (projectId) => ({ path: `/projects/${projectId}/tasks`, method: "GET" }),
  members: (projectId) => ({ path: `/projects/${projectId}/members`, method: "GET" }),
  phases: (projectId) => ({ path: `/projects/${projectId}/phases`, method: "GET" }),
  milestones: (projectId) => ({ path: `/projects/${projectId}/milestones`, method: "GET" }),
  teams: (projectId) => ({ path: `/projects/${projectId}/teams`, method: "GET" }),
  identifyTeamNeeds: (projectId) => ({ path: `/projects/${projectId}/identifyTeamNeeds`, method: "POST" }),
  defineJobRoles: (projectId) => ({ path: `/projects/${projectId}/defineJobRoles`, method: "POST" }),
  createJobDescriptions: (projectId) => ({ path: `/projects/${projectId}/createJobDescriptions`, method: "POST" }),
  advertisePositions: (projectId) => ({ path: `/projects/${projectId}/advertisePositions`, method: "POST" }),
  reviewApplications: (projectId) => ({ path: `/projects/${projectId}/reviewApplications`, method: "POST" }),
  conductInterviews: (projectId) => ({ path: `/projects/${projectId}/conductInterviews`, method: "POST" }),
  assessCulturalFit: (projectId) => ({ path: `/projects/${projectId}/assessCulturalFit`, method: "POST" }),
  checkReferences: (projectId) => ({ path: `/projects/${projectId}/checkReferences`, method: "POST" }),
  coordinateSelectionProcess: (projectId) => ({ path: `/projects/${projectId}/coordinateSelectionProcess`, method: "POST" }),
  onboardNewTeamMembers: (projectId) => ({ path: `/projects/${projectId}/onboardNewTeamMembers`, method: "POST" }),
  brainstormProduct: (projectId) => ({ path: `/projects/${projectId}/brainstormProduct`, method: "POST" }),
  launchProduct: (projectId) => ({ path: `/projects/${projectId}/launchProduct`, method: "POST" }),
  analyzeData: (projectId) => ({ path: `/projects/${projectId}/analyzeData`, method: "POST" }),
  rewardContributors: (projectId) => ({ path: `/projects/${projectId}/rewardContributors`, method: "POST" }),
  reinvestEarnings: (projectId) => ({ path: `/projects/${projectId}/reinvestEarnings`, method: "POST" }),
  buildCustomApp: (projectId) => ({ path: `/projects/${projectId}/buildCustomApp`, method: "POST" }),
  meetProjectMetrics: (projectId) => ({ path: `/projects/${projectId}/meetProjectMetrics`, method: "POST" }),
  generateRevenue: (projectId) => ({ path: `/projects/${projectId}/generateRevenue`, method: "POST" }),
  joinCommunityProject: (projectId) => ({ path: `/projects/${projectId}/joinCommunityProject`, method: "POST" }),
  promoteUnity: (projectId) => ({ path: `/projects/${projectId}/promoteUnity`, method: "POST" }),
  shareProjectProgress: (projectId) => ({ path: `/projects/${projectId}/shareProjectProgress`, method: "POST" }),
  celebrateMilestones: (projectId) => ({ path: `/projects/${projectId}/celebrateMilestones`, method: "POST" }),
  provideFeedback: (projectId) => ({ path: `/projects/${projectId}/provideFeedback`, method: "POST" }),
  inviteMembers: (projectId) => ({ path: `/projects/${projectId}/inviteMembers`, method: "POST" }),
  assignTasks: (projectId) => ({ path: `/projects/${projectId}/assignTasks`, method: "POST" }),
  scheduleMeetings: (projectId) => ({ path: `/projects/${projectId}/scheduleMeetings`, method: "POST" }),
  shareResources: (projectId) => ({ path: `/projects/${projectId}/shareResources`, method: "POST" }),
  trackProgress: (projectId) => ({ path: `/projects/${projectId}/trackProgress`, method: "POST" }),
  resolveConflicts: (projectId) => ({ path: `/projects/${projectId}/resolveConflicts`, method: "POST" }),
  resolveBugs: (projectId) => ({ path: `/projects/${projectId}/resolveBugs`, method: "POST" }),
  conductSurveys: (projectId) => ({ path: `/projects/${projectId}/conductSurveys`, method: "POST" }),
  facilitateTraining: (projectId) => ({ path: `/projects/${projectId}/facilitateTraining`, method: "POST" }),
  provideMentorship: (projectId) => ({ path: `/projects/${projectId}/provideMentorship`, method: "POST" }),
  ensureAccessibility: (projectId) => ({ path: `/projects/${projectId}/ensureAccessibility`, method: "POST" }),
  implementSecurityMeasures: (projectId) => ({ path: `/projects/${projectId}/implementSecurityMeasures`, method: "POST" }),
  ensurePrivacy: (projectId) => ({ path: `/projects/${projectId}/ensurePrivacy`, method: "POST" }),
  implementDataProtection: (projectId) => ({ path: `/projects/${projectId}/implementDataProtection`, method: "POST" }),
};
